export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_DISPLAYED_STAFF = 'SET_DISPLAYED_STAFF';
export const SET_DISPLAYED_DEPARTMENT = 'SET_DISPLAYED_DEPARTMENT';
export const SET_SELECTED_STAFF = 'SET_SELECTED_STAFF';
